### ISSUE TITLE
업체(Company) 기능 구현

### ISSUE THREAD

**Issue by eleunadeu** [Na-vi-9/msa#48]
## Description
Company CRUD 기능 구현

## Todo
- [x] API POST /companies
- [x] API GET /companies
- [x] API GET /companies/{companyUUID}
- [x] API PUT /companies/{companyUUID}
- [x] API DELETE /companies/{companyUUID}

**Comment by eleunadeu** [comment]
기능 개발 완료
